In [ ]:
"""
텍스트전처리
-토큰화(글자,단어,문장,문단)
-불용어
-정규표현식
-인코딩, 패딩
konlpy.org
"""


'\n텍스트전처리\n-토큰(글자,단어,문장,문단)화\n-불용어\n-정규표현식\n-인코딩, 패\n-아버지, 가방\n아버지가방에들어가신다 =>\nkonlpy.org\n'

In [ ]:
"""
자연어처리 환경 구성
1. 텐서플로우 설치
pip install tensorflow
2. nltk 설치
pip install nltk
설치 후
import nltk
nltk.download()
3. konlpy 설치
"""

'\n자연어처리 환경 구성\n1. 텐서플로우 설치\npip install tensorflow\n2. nltk 설치\npip install nltk\n설치 후\nimport nltk\nnltk.download()\n3. konlpy 설치\n\n'

In [ ]:
pip install konlpy

In [ ]:
import konlpy
from konlpy.tag import Okt

In [ ]:
# morphs : 형태소
okt = Okt()
print(okt.morphs(u'단독입찰보다 복수입찰의 경우'))

['단독', '입찰', '보다', '복수', '입찰', '의', '경우']


In [ ]:
print(okt.morphs(u'아버지가방에들어가신다'))

['아버지', '가방', '에', '들어가신다']


In [ ]:
"""
단어가방(Bag of words;BOW) : 단어들이 순서와 관계없이 저장,사전
코퍼스(corpus;말뭉치) : 자연어처리(분석)하고자 하는 분야와 관련된 단어 집합
ex) 법률서비스 챗봇-> 법률코퍼스:기소,벌금,...
"""

'\n단어가방(Bag of words;BOW)?단어들이 순서와 관계없이 저장,사전\n코퍼스(corpus;말뭉치)?자연어처리(분석)하고자 하는 분야와 관련된 \n단어 집합\nex) 법률서비스 챗봇-> 법률코퍼스:기소,벌금,...\n'

In [ ]:
#nltk : 영어 코퍼스 토큰화 도구
import nltk
from nltk.tokenize import word_tokenize, WordPunctTokenizer, sent_tokenize
# word_tokenize : 공백과 구두점을 기준으로 분리
# WordPunctTokenizer : 단어와 구두점을 모두 따로 분리
# sent_tokenize : 문장별로 쪼개어 리스트로 반환

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
print("단어 토큰화 결과 : ", word_tokenize("Tommy's Don't And that’s exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in."))

단어 토큰화 결과 :  ['Tommy', "'s", 'Do', "n't", 'And', 'that', '’', 's', 'exactly', 'the', 'way', 'with', 'our', 'machines', '.', 'In', 'order', 'to', 'get', 'our', 'computer', 'to', 'understand', 'any', 'text', ',', 'we', 'need', 'to', 'break', 'that', 'word', 'down', 'in', 'a', 'way', 'that', 'our', 'machine', 'can', 'understand', '.', 'That', '’', 's', 'where', 'the', 'concept', 'of', 'tokenization', 'in', 'Natural', 'Language', 'Processing', '(', 'NLP', ')', 'comes', 'in', '.']


In [ ]:
print("단어 토큰화 결과 : ", WordPunctTokenizer().tokenize("Tommy's Don't And that’s exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in."))

단어 토큰화 결과 :  ['Tommy', "'", 's', 'Don', "'", 't', 'And', 'that', '’', 's', 'exactly', 'the', 'way', 'with', 'our', 'machines', '.', 'In', 'order', 'to', 'get', 'our', 'computer', 'to', 'understand', 'any', 'text', ',', 'we', 'need', 'to', 'break', 'that', 'word', 'down', 'in', 'a', 'way', 'that', 'our', 'machine', 'can', 'understand', '.', 'That', '’', 's', 'where', 'the', 'concept', 'of', 'tokenization', 'in', 'Natural', 'Language', 'Processing', '(', 'NLP', ')', 'comes', 'in', '.']


In [ ]:
data="Language is a thing of beauty. But mastering a new language from scratch is quite a daunting prospect. If you’ve ever picked up a language that wasn’t your mother tongue, you’ll relate to this! There are so many layers to peel off and syntaxes to consider – it’s quite a challenge."


In [ ]:
sent_tokenize(data)

['Language is a thing of beauty.',
 'But mastering a new language from scratch is quite a daunting prospect.',
 'If you’ve ever picked up a language that wasn’t your mother tongue, you’ll relate to this!',
 'There are so many layers to peel off and syntaxes to consider – it’s quite a challenge.']

In [ ]:
# pos_tag : 품사 태깅. 각 단어에 대해 어떤 품사로 사용되는지 출력
from nltk.tag import pos_tag

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
print("단어 토큰화 결과 : ", word_tokenize("Tommy's Don't And that’s exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in."))
res=word_tokenize("Tommy's Don't And that’s exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in.")
pos_tag(res)

단어 토큰화 결과 :  ['Tommy', "'s", 'Do', "n't", 'And', 'that', '’', 's', 'exactly', 'the', 'way', 'with', 'our', 'machines', '.', 'In', 'order', 'to', 'get', 'our', 'computer', 'to', 'understand', 'any', 'text', ',', 'we', 'need', 'to', 'break', 'that', 'word', 'down', 'in', 'a', 'way', 'that', 'our', 'machine', 'can', 'understand', '.', 'That', '’', 's', 'where', 'the', 'concept', 'of', 'tokenization', 'in', 'Natural', 'Language', 'Processing', '(', 'NLP', ')', 'comes', 'in', '.']


[('Tommy', 'NNP'),
 ("'s", 'POS'),
 ('Do', 'VBP'),
 ("n't", 'RB'),
 ('And', 'CC'),
 ('that', 'IN'),
 ('’', 'NNP'),
 ('s', 'VBZ'),
 ('exactly', 'RB'),
 ('the', 'DT'),
 ('way', 'NN'),
 ('with', 'IN'),
 ('our', 'PRP$'),
 ('machines', 'NNS'),
 ('.', '.'),
 ('In', 'IN'),
 ('order', 'NN'),
 ('to', 'TO'),
 ('get', 'VB'),
 ('our', 'PRP$'),
 ('computer', 'NN'),
 ('to', 'TO'),
 ('understand', 'VB'),
 ('any', 'DT'),
 ('text', 'NN'),
 (',', ','),
 ('we', 'PRP'),
 ('need', 'VBP'),
 ('to', 'TO'),
 ('break', 'VB'),
 ('that', 'IN'),
 ('word', 'NN'),
 ('down', 'RP'),
 ('in', 'IN'),
 ('a', 'DT'),
 ('way', 'NN'),
 ('that', 'IN'),
 ('our', 'PRP$'),
 ('machine', 'NN'),
 ('can', 'MD'),
 ('understand', 'VB'),
 ('.', '.'),
 ('That', 'DT'),
 ('’', 'VBZ'),
 ('s', 'NN'),
 ('where', 'WRB'),
 ('the', 'DT'),
 ('concept', 'NN'),
 ('of', 'IN'),
 ('tokenization', 'NN'),
 ('in', 'IN'),
 ('Natural', 'NNP'),
 ('Language', 'NNP'),
 ('Processing', 'NNP'),
 ('(', '('),
 ('NLP', 'NNP'),
 (')', ')'),
 ('comes', 'VBZ'),
 ('in'

In [ ]:
pip install kss

In [ ]:
# kss : 한국어 문장 토큰화 도구
# 대문자로 시작하는 것은 클래스이므로 객체 생성필요
import kss
from konlpy.tag import Okt, Kkma

In [ ]:
text="여름입니다. 날씨가 덥습니다! 딥러닝을 공부합니다. 네?"

In [ ]:
kss.split_sentences(text)

['여름입니다.', '날씨가 덥습니다!', '딥러닝을 공부합니다.', '네?']

In [ ]:
okt=Okt()
kkma=Kkma()

In [ ]:
print("Okt : ", okt.morphs("NLP를 열심히 공부하고, 취업에 성공합시다"))
print("Okt : ", okt.pos("NLP를 열심히 공부하고, 취업에 성공합시다"))
print("Okt : ", okt.nouns("NLP를 열심히 공부하고, 취업에 성공합시다"))

Okt :  ['NLP', '를', '열심히', '공부', '하고', ',', '취업', '에', '성공합시다']
Okt :  [('NLP', 'Alpha'), ('를', 'Noun'), ('열심히', 'Adverb'), ('공부', 'Noun'), ('하고', 'Josa'), (',', 'Punctuation'), ('취업', 'Noun'), ('에', 'Josa'), ('성공합시다', 'Adjective')]
Okt :  ['를', '공부', '취업']


In [ ]:
print("kkma : ", kkma.morphs("NLP를 열심히 공부하고, 취업에 성공합시다"))
print("kkma : ", kkma.pos("NLP를 열심히 공부하고, 취업에 성공합시다"))
print("kkma : ", kkma.nouns("NLP를 열심히 공부하고, 취업에 성공합시다"))

kkma :  ['NLP', '를', '열심히', '공부', '하', '고', ',', '취업', '에', '성공', '합', '시다']
kkma :  [('NLP', 'OL'), ('를', 'JKO'), ('열심히', 'MAG'), ('공부', 'NNG'), ('하', 'XSV'), ('고', 'ECE'), (',', 'SP'), ('취업', 'NNG'), ('에', 'JKM'), ('성공', 'NNG'), ('합', 'NNG'), ('시다', 'NNG')]
kkma :  ['공부', '취업', '성공', '성공합시다', '합', '시다']


In [ ]:
#빈도수가 낮거나, 길이가 매우 짧은 단어는 상황에 따라 제거 고려.

In [ ]:
import re #정규표현식
text="Tommy's Don't And that's exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in."

In [ ]:
pat=re.compile(r'\W*\b\w{1,2}\b')

In [ ]:
# pat에 대응되는 부분을 빈 문자열로 대체
pat.sub('',text)

'Tommy Don And that exactly the way with our machines order get our computer understand any text need break that word down way that our machine can understand. That where the concept tokenization Natural Language Processing (NLP) comes.'

In [ ]:
# 불용어를 제공하는 패키지 (불용어 : 의미가 없는 단어, 조사)
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
text

"Tommy's Don't And that's exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in."

In [ ]:
len(set(stopwords.words("english"))) #179
sw=set(stopwords.words("english")) #중복방지

In [ ]:
# 불용어 제거단계
# 단어들로 분해하여 불용어리스트에 없다면 res에 추가
wt=word_tokenize(text)
res=[]
for w in wt:
    if w not in sw:
        res.append(w)

In [ ]:
print(wt)
print(len(wt))

['Tommy', "'s", 'Do', "n't", 'And', 'that', "'s", 'exactly', 'the', 'way', 'with', 'our', 'machines', '.', 'In', 'order', 'to', 'get', 'our', 'computer', 'to', 'understand', 'any', 'text', ',', 'we', 'need', 'to', 'break', 'that', 'word', 'down', 'in', 'a', 'way', 'that', 'our', 'machine', 'can', 'understand', '.', 'That', '’', 's', 'where', 'the', 'concept', 'of', 'tokenization', 'in', 'Natural', 'Language', 'Processing', '(', 'NLP', ')', 'comes', 'in', '.']
59


In [ ]:
print(res)
print(len(res))

['Tommy', "'s", 'Do', "n't", 'And', "'s", 'exactly', 'way', 'machines', '.', 'In', 'order', 'get', 'computer', 'understand', 'text', ',', 'need', 'break', 'word', 'way', 'machine', 'understand', '.', 'That', '’', 'concept', 'tokenization', 'Natural', 'Language', 'Processing', '(', 'NLP', ')', 'comes', '.']
36


In [ ]:
text="NLP를 열심히 공부하고, 취업에 성공합시다"
sw="를 에 고 라고 다"

In [ ]:
sw=sw.split(" ")
sw

['를', '에', '고', '라고', '다']

In [ ]:
wt=okt.morphs(text)
res=[w for w in wt if not w in sw]

In [ ]:
wt

['NLP', '를', '열심히', '공부', '하고', ',', '취업', '에', '성공합시다']

In [ ]:
res

['NLP', '열심히', '공부', '하고', ',', '취업', '성공합시다']

In [ ]:
#원핫인코딩
#단어 -> 정수화(index)
#good hi hello -> 0 1 2 => 100 010 001

In [ ]:
text="""
Tokenization is a key (and mandatory) aspect of working with text data
We’ll discuss the various nuances of tokenization, including how to handle Out-of-Vocabulary words (OOV)
Language is a thing of beauty. But mastering a new language from scratch is quite a daunting prospect. If you’ve ever picked up a language that wasn’t your mother tongue, you’ll relate to this! There are so many layers to peel off and syntaxes to consider – it’s quite a challenge.
And that’s exactly the way with our machines. In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand. That’s where the concept of tokenization in Natural Language Processing (NLP) comes in.
Simply put, we can’t work with text data if we don’t perform tokenization. Yes, it’s really that important!
"""

In [ ]:
sw=set(stopwords.words("english"))

In [ ]:
sents=sent_tokenize(text)

In [ ]:
sents
len(sents)#9

9

In [ ]:
vocab={}
pre_sents=[]
for s in sents: #문장 토큰화
    wt=word_tokenize(s)  #단어 토큰화 (단어 리스트)
    res=[]
    for w in wt:  # 각 단어 추출
        w=w.lower()
        if w not in sw: #불용어 리스트에 없고
            if len(w) > 2: # 길이가 2보다 크다면
                res.append(w)
                if w not in vocab: #vocab는 빈도를 기록하는 사전
                    vocab[w]=0
                vocab[w]+=1
    pre_sents.append(res) # pre_sents 는 문장들의 단어들 중 불용어 제거한 단어 리스트
print(pre_sents)

[['tokenization', 'key', 'mandatory', 'aspect', 'working', 'text', 'data', 'discuss', 'various', 'nuances', 'tokenization', 'including', 'handle', 'out-of-vocabulary', 'words', 'oov', 'language', 'thing', 'beauty'], ['mastering', 'new', 'language', 'scratch', 'quite', 'daunting', 'prospect'], ['ever', 'picked', 'language', 'mother', 'tongue', 'relate'], ['many', 'layers', 'peel', 'syntaxes', 'consider', 'quite', 'challenge'], ['exactly', 'way', 'machines'], ['order', 'get', 'computer', 'understand', 'text', 'need', 'break', 'word', 'way', 'machine', 'understand'], ['concept', 'tokenization', 'natural', 'language', 'processing', 'nlp', 'comes'], ['simply', 'put', 'work', 'text', 'data', 'perform', 'tokenization'], ['yes', 'really', 'important']]


In [ ]:
vocab
#vocab['and']

{'tokenization': 4,
 'key': 1,
 'mandatory': 1,
 'aspect': 1,
 'working': 1,
 'text': 3,
 'data': 2,
 'discuss': 1,
 'various': 1,
 'nuances': 1,
 'including': 1,
 'handle': 1,
 'out-of-vocabulary': 1,
 'words': 1,
 'oov': 1,
 'language': 4,
 'thing': 1,
 'beauty': 1,
 'mastering': 1,
 'new': 1,
 'scratch': 1,
 'quite': 2,
 'daunting': 1,
 'prospect': 1,
 'ever': 1,
 'picked': 1,
 'mother': 1,
 'tongue': 1,
 'relate': 1,
 'many': 1,
 'layers': 1,
 'peel': 1,
 'syntaxes': 1,
 'consider': 1,
 'challenge': 1,
 'exactly': 1,
 'way': 2,
 'machines': 1,
 'order': 1,
 'get': 1,
 'computer': 1,
 'understand': 2,
 'need': 1,
 'break': 1,
 'word': 1,
 'machine': 1,
 'concept': 1,
 'natural': 1,
 'processing': 1,
 'nlp': 1,
 'comes': 1,
 'simply': 1,
 'put': 1,
 'work': 1,
 'perform': 1,
 'yes': 1,
 'really': 1,
 'important': 1}

In [ ]:
vocab
#빈도수가 높은 순서대로 정렬하여 출력
#[('that', 6), ...]
# x=[10,30,20,25]
# sorted(x, reverse=True)

vocab.items()
vs=sorted(vocab.items(), key=lambda x:x[1], reverse=True) #x에는 ('tokenization', 4).. 앞의 매개변수 vocab.items 전달
vs

[('tokenization', 4),
 ('language', 4),
 ('text', 3),
 ('data', 2),
 ('quite', 2),
 ('way', 2),
 ('understand', 2),
 ('key', 1),
 ('mandatory', 1),
 ('aspect', 1),
 ('working', 1),
 ('discuss', 1),
 ('various', 1),
 ('nuances', 1),
 ('including', 1),
 ('handle', 1),
 ('out-of-vocabulary', 1),
 ('words', 1),
 ('oov', 1),
 ('thing', 1),
 ('beauty', 1),
 ('mastering', 1),
 ('new', 1),
 ('scratch', 1),
 ('daunting', 1),
 ('prospect', 1),
 ('ever', 1),
 ('picked', 1),
 ('mother', 1),
 ('tongue', 1),
 ('relate', 1),
 ('many', 1),
 ('layers', 1),
 ('peel', 1),
 ('syntaxes', 1),
 ('consider', 1),
 ('challenge', 1),
 ('exactly', 1),
 ('machines', 1),
 ('order', 1),
 ('get', 1),
 ('computer', 1),
 ('need', 1),
 ('break', 1),
 ('word', 1),
 ('machine', 1),
 ('concept', 1),
 ('natural', 1),
 ('processing', 1),
 ('nlp', 1),
 ('comes', 1),
 ('simply', 1),
 ('put', 1),
 ('work', 1),
 ('perform', 1),
 ('yes', 1),
 ('really', 1),
 ('important', 1)]

In [ ]:
#빈도수가 2이상인 단어들에 대해서 index를(1번~) 부여
word_index={}
a=0
for w, f in vs:
    if f>=2:
        a+=1
        word_index[w]=a
word_index

{'tokenization': 1,
 'language': 2,
 'text': 3,
 'data': 4,
 'quite': 5,
 'way': 6,
 'understand': 7}

In [ ]:
sents

['\nTokenization is a key (and mandatory) aspect of working with text data\nWe’ll discuss the various nuances of tokenization, including how to handle Out-of-Vocabulary words (OOV)\nLanguage is a thing of beauty.',
 'But mastering a new language from scratch is quite a daunting prospect.',
 'If you’ve ever picked up a language that wasn’t your mother tongue, you’ll relate to this!',
 'There are so many layers to peel off and syntaxes to consider – it’s quite a challenge.',
 'And that’s exactly the way with our machines.',
 'In order to get our computer to understand any text, we need to break that word down in a way that our machine can understand.',
 'That’s where the concept of tokenization in Natural Language Processing (NLP) comes in.',
 'Simply put, we can’t work with text data if we don’t perform tokenization.',
 'Yes, it’s really that important!']

In [ ]:
word_index

{'tokenization': 1,
 'language': 2,
 'text': 3,
 'data': 4,
 'quite': 5,
 'way': 6,
 'understand': 7}

In [ ]:
word_index['OOV']=len(word_index)+1 #Out Of Vocab

In [ ]:
enc_sents=[]
for s in pre_sents:
    enc_sent=[]
    for w in s:
        try:
            enc_sent.append(word_index[w])
        except KeyError:
            enc_sent.append(word_index['OOV'])
    enc_sents.append(enc_sent)
enc_sents

[[1, 8, 8, 8, 8, 3, 4, 8, 8, 8, 1, 8, 8, 8, 8, 8, 2, 8, 8],
 [8, 8, 2, 8, 5, 8, 8],
 [8, 8, 2, 8, 8, 8],
 [8, 8, 8, 8, 8, 5, 8],
 [8, 6, 8],
 [8, 8, 8, 7, 3, 8, 8, 8, 6, 8, 7],
 [8, 1, 8, 2, 8, 8, 8],
 [8, 8, 8, 3, 4, 8, 1],
 [8, 8, 8]]

In [ ]:
# 데이터수집(크롤링)도구:selenium, beautifulsoup4...
# 시각화도구: matplotlib,plotly,tableau,seaborn,folium
# 데이터분석도구:numpy,pandas
# 머신러닝도구:scikit-learn
# 딥러닝 프레임웍:텐서플로우(케라스), 파이토치, 까페, ...

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
#pre_sents
tok=Tokenizer()
tok.fit_on_texts(pre_sents) #모든 단어에 대해 번호를 부여

In [ ]:
tok.word_index
tok.word_counts

OrderedDict([('tokenization', 4),
             ('key', 1),
             ('mandatory', 1),
             ('aspect', 1),
             ('working', 1),
             ('text', 3),
             ('data', 2),
             ('discuss', 1),
             ('various', 1),
             ('nuances', 1),
             ('including', 1),
             ('handle', 1),
             ('out-of-vocabulary', 1),
             ('words', 1),
             ('oov', 1),
             ('language', 4),
             ('thing', 1),
             ('beauty', 1),
             ('mastering', 1),
             ('new', 1),
             ('scratch', 1),
             ('quite', 2),
             ('daunting', 1),
             ('prospect', 1),
             ('ever', 1),
             ('picked', 1),
             ('mother', 1),
             ('tongue', 1),
             ('relate', 1),
             ('many', 1),
             ('layers', 1),
             ('peel', 1),
             ('syntaxes', 1),
             ('consider', 1),
             ('challenge', 1)

In [ ]:
#패딩: 단어(PAD)에 대해 0으로 설정하여 길이를 맞춤

In [ ]:
pre_sentences = [['driver', 'person'], ['driver', 'good', 'person'], ['driver', 'huge', 'person'], ['knew', 'bad'], ['bad', 'kept', 'huge', 'bad'], ['huge', 'bad']]

In [ ]:
#단어 정수 인코딩
tok=Tokenizer()
tok.fit_on_texts(pre_sentences) #모든 단어에 대해 번호를 부여

In [ ]:
encoded=tok.texts_to_sequences(pre_sentences) #길이 4로 통일 (가장 긴 문장의 길이를 기준으로 패딩)
encoded

[[2, 3], [2, 5, 3], [2, 4, 3], [6, 1], [1, 7, 4, 1], [4, 1]]

In [ ]:
maxlen=max(len(i) for i in encoded)
maxlen

4

In [ ]:
for s in encoded:
    while len(s) < maxlen:
        s.append(0)

In [ ]:
s

[4, 1, 0, 0]

In [ ]:
encoded

[[2, 3, 0, 0],
 [2, 5, 3, 0],
 [2, 4, 3, 0],
 [6, 1, 0, 0],
 [1, 7, 4, 1],
 [4, 1, 0, 0]]

In [ ]:
import numpy as np

In [ ]:
np.array(encoded)

array([[2, 3, 0, 0],
       [2, 5, 3, 0],
       [2, 4, 3, 0],
       [6, 1, 0, 0],
       [1, 7, 4, 1],
       [4, 1, 0, 0]])

In [ ]:
#사실상 가장 중요한 부분 *******
#케라스 도구를 이용한 패딩(많이 사용됨)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
encoded=tok.texts_to_sequences(pre_sentences)
encoded

[[2, 3], [2, 5, 3], [2, 4, 3], [6, 1], [1, 7, 4, 1], [4, 1]]

In [ ]:
padded=pad_sequences(encoded, padding='post', maxlen=10) #pre가 기본값
padded

array([[2, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 5, 3, 0, 0, 0, 0, 0, 0, 0],
       [2, 4, 3, 0, 0, 0, 0, 0, 0, 0],
       [6, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 7, 4, 1, 0, 0, 0, 0, 0, 0],
       [4, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
padded=pad_sequences(encoded, maxlen=4)
padded

array([[0, 0, 2, 3],
       [0, 2, 5, 3],
       [0, 2, 4, 3],
       [0, 0, 6, 1],
       [1, 7, 4, 1],
       [0, 0, 4, 1]], dtype=int32)

In [ ]:
padded=pad_sequences(encoded, maxlen=2, truncating='post')
padded

array([[2, 3],
       [2, 5],
       [2, 4],
       [6, 1],
       [1, 7],
       [4, 1]], dtype=int32)

In [ ]:
padded=pad_sequences(encoded, maxlen=2, truncating='pre')
padded

array([[2, 3],
       [5, 3],
       [4, 3],
       [6, 1],
       [4, 1],
       [4, 1]], dtype=int32)

In [ ]:
#원핫인코딩
#단어 종류 : 10개 -> 인코딩 => 머신러닝/딥러닝 언어모델링(분류/생성/이해...)
#1~10번까지 번호 부여(1:sky, 2:computer, 3:pencil, ...)

# sky:      1000000000
# computer: 0100000000
# ...

In [ ]:
"""
단어의 종류가 10만개
원핫인코딩하면 각 단어는 10만차원 벡터공간에 임베딩
 sky: 1000000000...00000(원핫벡터) -> 차원 감소 -> [1.7 -3.5 0.3 0.1 0.2] 5차원 벡터공간 임베딩(밀집벡터)
"""

'\n단어의 종류가 10만개\n원핫인코딩하면 각 단어는 10만차원 벡터공간에 임베딩\n sky: 1000000000...00000(원핫벡터) -> 차원 감소 -> [1.7 -3.5 0.3 0.1 0.2] 5차원 벡터공간 임베딩(밀집벡터)'

In [ ]:
tokens=okt.morphs("자연어처리 공부를 합니다")
tokens

['자연어', '처리', '공부', '를', '합니다']

In [ ]:
# 10000(자연어)
# 01000(처리)

In [ ]:
#코퍼스(수집한 문서 전체)
text="점심 메뉴로 소고기볶음밥 먹었습니다. 소고기볶음밥 너무 맛있어요. 또 먹을래요."

In [ ]:
tok=Tokenizer()
tok.fit_on_texts([text]) #모든 단어에 대해 번호를 부여

In [ ]:
tok.word_index

{'소고기볶음밥': 1,
 '점심': 2,
 '메뉴로': 3,
 '먹었습니다': 4,
 '너무': 5,
 '맛있어요': 6,
 '또': 7,
 '먹을래요': 8}

In [ ]:
test="내일 메뉴로 소고기볶음밥 또 나왔으면 좋겠다."

In [ ]:
encoded=tok.texts_to_sequences([test])[0]  # 이차원 리스트에서 추출
encoded

[3, 1, 7]

In [ ]:
from tensorflow.keras.utils import to_categorical
# 이진화 원핫인코딩

In [ ]:
o_v=to_categorical(encoded)

In [ ]:
o_v

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
# 홍길동 영화 -> 추천?
# -영화의 줄거리를 기반으로 추천(tfidf -> consine sim -> 추천)

In [ ]:
import re

In [ ]:
text="""
[앵커]

오후가 되면서 비구름이 약해졌지만 내일 새벽부터 다시 전국에 비가 내리겠습니다.

특히, 호남지방은 내일까지 많게는 최대 120mm의 비가 예보됐습니다.

기상센터 연결해 자세한 장맛비 상황 알아보겠습니다.

김규리 캐스터! 현재, 비는 어느 지역에 집중되고 있나요?

[답변]

네, 현재는 남해안과 제주에 시간당 20mm의 세찬 비가 내리고 있습니다.

이에 경남과 전남 남해안, 제주에 호우주의보가 발효 중입니다.

어젯밤사이에는 광주, 전남에 폭우가 내렸습니다.

어제부터 오늘까지 전남 무안에 255mm의 많은 비가 쏟아졌고요.

광주도 145mm의 큰 비가 집중됐습니다.

현재 보이는 화면은 광주 황룡강의 모습입니다.

폭우가 집중되며 오늘 새벽 홍수주의보가 내려졌습니다.

현재는, 광주·전남 등 내륙 지역은 대부분 소강상태를 보이고 있습니다.

지금도 흙탕물에 나무가 잠겨 있지만 홍수주의보 기준인 5.5m 아래로 낮아지고 있습니다.

[앵커]

내일 새벽부터 다시 빗줄기가 강해질텐데, 얼마나 더 오는건가요?
"""

In [ ]:
print(re.findall('\w+mm', text))
#re.match(패턴, 문자열)
#a#문자열 내에 패턴이 존재합니까?
#패턴이 있다면 매치 결과가 출력
#없다면 None

['120mm', '20mm', '255mm', '145mm']
