1. 데이터 수집
- DB
- 웹크롤링(스크래핑), selenium, BeautifulSoup
- 텍스트 증식 고려(권장하지 않음)
- 위키피디아, 북스코퍼스 등
- 기타
2. 데이터 전처리
- 토큰화, 정제, 불용어 처리, 인코딩, 패딩 등
3. 언어 모델링
- 알고리즘 선택(ML, DL, DM)



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import re

In [4]:
"""
언어모델 : 통계적 모델, 신경망(기반) 모델
나는 오늘 강의실에서 자연어처리를 ?

통계적 모델 : 단어의 순서에 대해 확률이 부여
P(나는 자연어 처리를 공부한다) > P(나는 자연어 처리를 먹는다)
P(공부한다|나는, 자연어, 처리를)

n-gram : 문서(장,단)간 유사
'오늘 점심 추천 메뉴:소고기볶음밥, 햄볶음밥'
유니그램(n=1) : 오늘, 점심, 추천, 메뉴,소고기볶음밥, 햄볶음밥
바이그램(n=2) : 오늘 점심,점심 추천,추천 메뉴,메뉴 소고기볶음밥,소고기볶음밥 햄볶음밥
Trigram(n=3)
...

P(소고기볶음밥|점심 추천 메뉴)=
 count(점심 추천 메뉴 소고기볶음밥)   / count(점심 추천 메뉴)
 = 20/30
P(햄볶음밥|점심 추천 메뉴)=
 count(점심 추천 메뉴 햄볶음밥)   / count(점심 추천 메뉴)
 = 5/30
...

점심 추천 메뉴 ?(소고기볶음밥)

*시간이 되면 LCS(Longest Common Subsequence) 알고리즘 공부

1. 한국어는 단어의 순서가 큰 의미 없음 -> 신경망(RNN, LSTM) 기반 생성시 어려움
LinearRegression(예측, 회귀)-> LogisticRegression(이진분류, sigmoid) -> SOFTMAX(다중분류) -> (얕은)신경망(입력/출력계층존재) : NN
(깊은)신경망(입력/히든1개이상/출력) 종류 : DNN, CNN, RNN 등

h(x)=wx+b
sigmoid(h(x)) =  1 / (1+e-(h(x)))

나는 지금 자연어 공부해요
자연어 공부해요 나는 지금


"""

"\n언어모델 : 통계적 모델, 신경망(기반) 모델\n나는 오늘 강의실에서 자연어처리를 ?\n\n통계적 모델 : 단어의 순서에 대해 확률이 부여\nP(나는 자연어 처리를 공부한다) > P(나는 자연어 처리를 먹는다)\nP(공부한다|나는, 자연어, 처리를)\n\nn-gram : 문서(장,단)간 유사\n'오늘 점심 추천 메뉴:소고기볶음밥, 햄볶음밥'\n유니그램(n=1) : 오늘, 점심, 추천, 메뉴,소고기볶음밥, 햄볶음밥\n바이그램(n=2) : 오늘 점심,점심 추천,추천 메뉴,메뉴 소고기볶음밥,소고기볶음밥 햄볶음밥\nTrigram(n=3)\n...\n\nP(소고기볶음밥|점심 추천 메뉴)=\n count(점심 추천 메뉴 소고기볶음밥)   / count(점심 추천 메뉴)\n = 20/30\nP(햄볶음밥|점심 추천 메뉴)=\n count(점심 추천 메뉴 햄볶음밥)   / count(점심 추천 메뉴)\n = 5/30\n...\n\n점심 추천 메뉴 ?(소고기볶음밥)\n\n*시간이 되면 LCS(Longest Common Subsequence) 알고리즘 공부\n\n1. 한국어는 단어의 순서가 큰 의미 없음 -> 신경망(RNN, LSTM) 기반 생성시 어려움\nLinearRegression(예측, 회귀)-> LogisticRegression(이진분류, sigmoid) -> SOFTMAX(다중분류) -> (얕은)신경망(입력/출력계층존재) : NN\n(깊은)신경망(입력/히든1개이상/출력) 종류 : DNN, CNN, RNN 등\n\nh(x)=wx+b\nsigmoid(h(x)) =  1 / (1+e-(h(x)))\n\n나는 지금 자연어 공부해요\n자연어 공부해요 나는 지금\n\n\n"

In [5]:
"""
one-hot, DTM(Document Term Matrix, TF), TDM,  TFIDF(TF*IDF)
      단어1 단어2 ... 단어M
문서1   5     0   ...   1      M차원벡터공간(5,0,...,1)
문서2
...
문서N


"""

'\none-hot, DTM(Document Term Matrix, TF), TDM,  TFIDF(TF*IDF)\n      단어1 단어2 ... 단어M\n문서1   5     0   ...   1      M차원벡터공간(5,0,...,1)\n문서2\n...\n문서N\n\n\n'

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
#CountVectorizer:단어의 빈도수로 벡터 생성

In [8]:
corpus=['나는 지금 자연어 처리를 공부해요. 나는 자연어 좋아요.']
vector=CountVectorizer()

In [9]:
vector.fit_transform(corpus)
#fit:각각의 단어별로 인덱스 부여(0~5)
#transform: corpus에 저장된 문장을 fit 결과에 맞춰 변환(빈도수)해라=> [2 1 2 1 1 1]
# sparse matrix(희소행렬:행렬 요소값이 대부분 0인 행렬=>공간낭비,연산량이 많음)
# [
#     [2 1 2 1 1 1]
# ]
vector.fit_transform(corpus).toarray()

array([[1, 2, 2, 1, 1, 1]])

In [10]:
vector.vocabulary_

{'나는': 1, '지금': 4, '자연어': 2, '처리를': 5, '공부해요': 0, '좋아요': 3}

In [11]:
# 코사인 유사도를 사용해 DTM (유사한 문서 찾기, But, 단순 많이,적게 등장했다고 해서 중요한 단어일까??)
# > tfidf 변환(특정 단어가 특정 문서에서 자주 등장하고 전체 문서 집합에서 희귀할수록 높은 값 => 해당 문서에서 중요 )

#  DTM : 텍스트 데이터를 수치적인 형태로 변환 - CountVectorizer 사용하여 단어의 빈도수 확인
# 문서 유사도 : 얼마나 많은 단어가 공통적으로 들어있는지

# tf(d,t) : 문서 d에서 단어 t의 등장 횟수(DTM에서 행렬의 요소값이 tf임)
# df(t) : 단어 t가 등장한 문서의 개수
# idf(d,t) : log(n / (df(t)+1))
# - n은 전체 문서의 개수
# - log

# ex) n=1000

# idf(d,t)=log(1000 / (df(t)+1))
# df(t) =1, idf(d,t)는 log(1000/1)은 3
# df(t) =10, idf(d,t)는 log(1000/10)은 2

# tfidf=tf*idf
# 특정 단어가 많이 등장하면서, 흔치 않은 단어여야 함
# 특정 단어가 특정 문서에서 자주 등장하고 전체 문서 집합에서 희귀할수록 높은 값을 갖게 됩니다.

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [13]:
corpus=[
        'I do love you', #문서1
        'I can do it love', #문서2
        'I want your love'     #문서3
]

In [14]:
v=CountVectorizer()

In [15]:
v.fit_transform(corpus).toarray()

array([[0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1]])

In [16]:
v.vocabulary_

{'do': 1, 'love': 3, 'you': 5, 'can': 0, 'it': 2, 'want': 4, 'your': 6}

In [17]:
tfv=TfidfVectorizer()
print(tfv.fit_transform(corpus).toarray())

[[0.         0.54783215 0.         0.42544054 0.         0.72033345
  0.        ]
 [0.5844829  0.44451431 0.5844829  0.34520502 0.         0.
  0.        ]
 [0.         0.         0.         0.38537163 0.65249088 0.
  0.65249088]]


In [18]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [19]:
#d1,d2,d3는 영화제목
#각 열은 영화 대사에 등장한 단어(사랑,돈,운명,증오)
d1=np.array([1,1,1,0])#루트2
d2=np.array([0,1,1,1])
d3=np.array([0,5,5,5])#루트48
#유클리디안 거리 공식으로는 d2문서가 d1과 가까움

In [20]:
dot(d1, d2) / (norm(d1)*norm(d2)) #0.67

0.6666666666666667

In [21]:
dot(d3, d2) / (norm(d3)*norm(d2)) #1

1.0

In [22]:
#자카드 유사도, 집합의 원소는 단어에 해당됨, 0~1
#자카드유사도(d1,d2)=(d1 교집합 d2) / (d1 합집합 d2)

In [ ]:
# 코사인유사도 영화추천시스템 개발

In [25]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/NLP/dataset/movies_metadata.csv")
df

<ipython-input-26-e686b7385c1a>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/NLP/dataset/movies_metadata.csv")


adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      False                                                NaN  65000000   
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      False                                                NaN  16000000   
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...      ...                                                ...       ...   
45461  False                                                NaN         0   
45462  False                                                NaN         0   
45463  False                                                NaN         0   
45464  False                                                NaN         0   
45465  False                                                NaN         0   

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                         [{'id': 35, 'name': 'Comedy'}]   
...                                                  ...   
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   
45462                      [{'id': 18, 'name': 'Drama'}]   
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...   
45464                                                 []   
45465                                                 []   

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709   
1                                       NaN    8844  tt0113497   
2                                       NaN   15602  tt0113228   
3                                       NaN   31357  tt0114885   
4                                       NaN   11862  tt0113041   
...                                     ...     ...        ...   
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470   
45462                                   NaN  111109  tt2028550   
45463                                   NaN   67758  tt0303758   
45464                                   NaN  227506  tt0008536   
45465                                   NaN  461257  tt6980792   

      original_language               original_title  \
0                    en                    Toy Story   
1                    en                      Jumanji   
2                    en             Grumpier Old Men   
3                    en            Waiting to Exhale   
4                    en  Father of the Bride Part II   
...                 ...                          ...   
45461                fa                      رگ خواب   
45462                tl          Siglo ng Pagluluwal   
45463                en                     Betrayal   
45464                en          Satana likuyushchiy   
45465                en                     Queerama   

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2      A family wedding reignites the ancient feud be...  ...   1995-12-22   
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4      Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                  ...  ...          ...   
45461        Rising and falling between a man and woman.  ...          NaN   
45462  An artist struggles to finish his work while a...  ...   2011-11-17   
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01   
45464  In a small town live two brothers, one a minis...  ...   1917-10-21   
45465  50 years after decriminalisati

In [27]:
df=df.head(10000)

In [28]:
df

adult                              belongs_to_collection    budget  \
0     False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1     False                                                NaN  65000000   
2     False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3     False                                                NaN  16000000   
4     False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...     ...                                                ...       ...   
9995  False                                                NaN         0   
9996  False                                                NaN   4500000   
9997  False                                                NaN   9200000   
9998  False                                                NaN         0   
9999  False  {'id': 124879, 'name': 'State Property Collect...         0   

                                                 genres  \
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                        [{'id': 35, 'name': 'Comedy'}]   
...                                                 ...   
9995  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...   
9996                      [{'id': 18, 'name': 'Drama'}]   
9997  [{'id': 37, 'name': 'Western'}, {'id': 35, 'na...   
9998  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...   
9999  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                  homepage     id    imdb_id  \
0     http://toystory.disney.com/toy-story    862  tt0114709   
1                                      NaN   8844  tt0113497   
2                                      NaN  15602  tt0113228   
3                                      NaN  31357  tt0114885   
4                                      NaN  11862  tt0113041   
...                                    ...    ...        ...   
9995                                   NaN  43379  tt0043809   
9996                                   NaN   9393  tt0384369   
9997                                   NaN  16972  tt0079180   
9998                                   NaN  21325  tt0355857   
9999                                   NaN  13409  tt0403537   

     original_language                 original_title  \
0                   en                      Toy Story   
1                   en                        Jumanji   
2                   en               Grumpier Old Men   
3                   en              Waiting to Exhale   
4                   en    Father of the Bride Part II   
...                ...                            ...   
9995                it              Miracolo a Milano   
9996                de  Napola – Elite für den Führer   
9997                en                 The Frisco Kid   
9998                ja                        Onmyoji   
9999                en               State Property 2   

                                               overview  ... release_date  \
0     Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1     When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2     A family wedding reignites the ancient feud be...  ...   1995-12-22   
3     Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4     Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                 ...  ...          ...   
9995  Once upon a time an old woman discovers a baby...  ...   1951-02-08   
9996  In 1942, Friedrich Weimer's boxing skills get ...  ...   2004-07-04   
9997  Rabbi Avram arrives in Philadelphia from Polan...  ...   1979-07-06   
9998  During a dark time in the Heian period, when e...  ...   2001-10-06   
9999  Three gangsters vie for control of the streets...  ...   2005-04-13   

     

In [29]:
#df.info()
df.isnull().sum(axis=0)

adult                       0
belongs_to_collection    8579
budget                      0
genres                      0
homepage                 9338
id                          0
imdb_id                     1
original_language           0
original_title              0
overview                   29
popularity                  0
poster_path                31
production_companies        0
production_countries        0
release_date                5
revenue                     0
runtime                     6
spoken_languages            0
status                      8
tagline                  3108
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [30]:
df['overview']=df['overview'].fillna('')

<ipython-input-30-d9c55157cecf>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview']=df['overview'].fillna('')


In [31]:
df['overview'].isnull().sum()

0

In [32]:
tfidf=TfidfVectorizer(stop_words='english')

In [33]:
tfidf_m=tfidf.fit_transform(df['overview'])
tfidf_m.shape

(10000, 32350)

In [34]:
tfidf_m

<10000x32350 sparse matrix of type '<class 'numpy.float64'>'
	with 268918 stored elements in Compressed Sparse Row format>

In [35]:
cos_sim=cosine_similarity(tfidf_m, tfidf_m)

In [36]:
cos_sim.shape

(10000, 10000)

In [37]:
cos_sim[0]

array([1.        , 0.01682915, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [38]:
df['title']
df.index

RangeIndex(start=0, stop=10000, step=1)

In [39]:
data=dict(zip(df['title'],df.index))
i=data['Toy Story']
print(i)

0


In [44]:
# 다른방법 : enumerate로도 표현 가능
# titles = df['title']
# data = {title: index for index, title in enumerate(titles)}  # title:index : dictionary의 key-value 값

# i = data['Toy Story']
# print(i)

0


In [40]:
data

{'Toy Story': 0,
 'Jumanji': 1,
 'Grumpier Old Men': 2,
 'Waiting to Exhale': 3,
 'Father of the Bride Part II': 4,
 'Heat': 5,
 'Sabrina': 888,
 'Tom and Huck': 7,
 'Sudden Death': 8,
 'GoldenEye': 9,
 'The American President': 10,
 'Dracula: Dead and Loving It': 11,
 'Balto': 12,
 'Nixon': 13,
 'Cutthroat Island': 14,
 'Casino': 15,
 'Sense and Sensibility': 16,
 'Four Rooms': 17,
 'Ace Ventura: When Nature Calls': 18,
 'Money Train': 19,
 'Get Shorty': 20,
 'Copycat': 21,
 'Assassins': 22,
 'Powder': 23,
 'Leaving Las Vegas': 24,
 'Othello': 2733,
 'Now and Then': 26,
 'Persuasion': 27,
 'The City of Lost Children': 28,
 'Shanghai Triad': 29,
 'Dangerous Minds': 30,
 'Twelve Monkeys': 31,
 'Wings of Courage': 32,
 'Babe': 33,
 'Carrington': 34,
 'Dead Man Walking': 35,
 'Across the Sea of Time': 36,
 'It Takes Two': 37,
 'Clueless': 38,
 'Cry, the Beloved Country': 39,
 'Richard III': 7185,
 'Dead Presidents': 41,
 'Restoration': 42,
 'Mortal Kombat': 43,
 'To Die For': 44,
 'How To

In [48]:
# 사실 이 함수만 이해하면 간단한 추천 시스템 끝!!! 찬찬히 살펴보아요
def recommend(t, cosine_sim=cos_sim): #t에는 제목 전달
    idx=data[t]
    sim_scores=list(enumerate(cosine_sim[idx]))
    # print(sim_scores)
    ss=sorted(sim_scores, key=lambda x:x[1], reverse=True) # 연관성이 높다고 생각되는 상위 10개만 추출
    ss=ss[1:11]
    print(ss)
    res=[i[0] for i in ss]
    print(res)
    return df['title'].iloc[res]   # iloc 을 이용해 모든 행에 조건 인덱스만 가져오기


In [49]:
recommend('Toy Story')

[(2997, 0.45638472239975103), (8327, 0.2125051726227112), (1071, 0.18331721941453483), (3057, 0.14787027144517378), (1932, 0.14188013382197434), (485, 0.14122665831617187), (5797, 0.13658886827487585), (7254, 0.1301910487191963), (6944, 0.12627898167423743), (7615, 0.12460340953655338)]
[2997, 8327, 1071, 3057, 1932, 485, 5797, 7254, 6944, 7615]


2997                                    Toy Story 2
8327                                      The Champ
1071                          Rebel Without a Cause
3057                                Man on the Moon
1932                                      Condorman
485                                          Malice
5797                                  Class of 1984
7254                                 Africa Screams
6944                               Rivers and Tides
7615    The First $20 Million Is Always the Hardest
Name: title, dtype: object