In [13]:
import torch
import numpy as np

## 3차원 텐서 (차원, 행, 열)

## 브로드캐스팅 : 자동으로 크기를 맞춰서 연산을 수행하는 기능

In [3]:
# 브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 굉장히 주의해서 사용해야 합니다. 
# 사용자가 두 텐서의 크기가 같다고 착각하고 덧셈 연산을 수행했다고 가정해보겠습니다. 
# 하지만 실제로 이 두 텐서의 크기는 달랐고 브로드캐스팅이 수행되어 덧셈 연산이 수행되었습니다.
# 두 텐서의 크기가 다르다고 에러를 발생시킨다면 연산이 잘못되었음을 알 수 있지만 
# 브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려움


# Vector + scalar                   차원이 일치하지 않음에도 결과 출력
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


## 차원이 다른 벡터간의 연산 (행렬, 원소 곱셈)

In [4]:
# 2 x 1 Vector + 1 x 2 Vector      차원이 다른 벡터간의 연산
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [5]:
# 행렬 곱셈. matmul()을 통해 수행합니다.

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [6]:
# 원소 별 곱셈. 브로드캐스트 진행 후, 행렬원소끼리 곱하는 것.

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [72]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력


# 덮어쓰기
print('\n덮어쓰기')
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

덮어쓰기
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## 텐서 연산

In [7]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())       # 전체 평균값
print(t.mean(dim=0))  # 입력에서 첫번째 차원(행)을 제거, 열의 평균값
print(t.mean(dim=1))  # 입력에서 첫번째 차원(열)을 제거, 행의 평균값
print(t.mean(dim=-1)) # 마지막 차원(열)을 제거

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [8]:
# 최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴
print(t.max(dim=0))    # max에 dim 인자를 주면 argmax도 함께 리턴

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


### view, squeeze, unsqueeze는 원소 수를 유지하며 모양과 차원을 조절

### view : 원소의 수를 유지하며 텐서 크기변경 (contigious)  reshape 비슷

In [18]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print(ft.view([-1, 3]).shape) # 2

torch.Size([2, 2, 3])
torch.Size([4, 3])


## squeeze : 1인 차원을 제거한다  <> unsqueeze : 차원 추가

In [20]:
# 3 by 1  2차원 텐서 > 1차원 벡터
ft = torch.FloatTensor([[0], [1], [2]])
print(ft.shape)
print(ft.squeeze().shape)

torch.Size([3, 1])
torch.Size([3])


In [34]:
# 1차원 벡터 > 2차원 텐서
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

# view를 이용한 2차원 만들기
print('\nView 사용')
print(ft.shape)
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])

View 사용
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


## 연결(concatenate)

In [36]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [37]:
print(torch.cat([x, y], dim=0)) # 행을 기준으로 concat

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [38]:
print(torch.cat([x, y], dim=1)) # 열을 기준으로 concat

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 스태킹

In [54]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [62]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [61]:
# 스태킹과 같은 작업 - 차원 변경후 연결
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

# 단순 연결하였을 떄, 구조가 다름   X,Y,Z 는 1차원 벡터이기 떄문
print(torch.cat([x, y, z], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([1., 4., 2., 5., 3., 6.])
