# 단순선형회귀분석

In [187]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)                 

In [188]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() 
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [189]:
# 학습 이후 파라미터 값 (weight, bias)
print('학습 이후 파라미터',list(model.parameters()))

학습 이후 파라미터 [Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [190]:
# 임의의 값을 넣어 예측 test
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


# 다중선형회귀분석

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)                 

In [194]:
torch.manual_seed(1) # 한번 사용되면 다시 시드 지정


x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # model(x_train)은 model.forward(x_train)와 동일함.
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


In [195]:
# 학습 이후 파라미터 값 (weight, bias)   - 생각보다 변동이 큼
print('학습 이후 파라미터',list(model.parameters()))

학습 이후 파라미터 [Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [196]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward0>)


# Mini-Batch 적용

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset 
from torch.utils.data import DataLoader # 데이터로더

In [53]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
# x_train, y_train 결합
dataset = TensorDataset(x_train, y_train)

# DataLoader : Mini-Batch 묶기, 효율적인 데이터 로딩 및 학습
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
            ))


Epoch    0/20 Batch 1/3 Cost: 7139.530273
Epoch    0/20 Batch 2/3 Cost: 2163.698730
Epoch    0/20 Batch 3/3 Cost: 1129.725464
Epoch    1/20 Batch 1/3 Cost: 176.478180
Epoch    1/20 Batch 2/3 Cost: 53.319839
Epoch    1/20 Batch 3/3 Cost: 18.632021
Epoch    2/20 Batch 1/3 Cost: 2.259949
Epoch    2/20 Batch 2/3 Cost: 5.099573
Epoch    2/20 Batch 3/3 Cost: 5.797091
Epoch    3/20 Batch 1/3 Cost: 1.514429
Epoch    3/20 Batch 2/3 Cost: 1.648437
Epoch    3/20 Batch 3/3 Cost: 3.328553
Epoch    4/20 Batch 1/3 Cost: 1.843488
Epoch    4/20 Batch 2/3 Cost: 1.954591
Epoch    4/20 Batch 3/3 Cost: 1.615935
Epoch    5/20 Batch 1/3 Cost: 1.754194
Epoch    5/20 Batch 2/3 Cost: 0.706354
Epoch    5/20 Batch 3/3 Cost: 4.578487
Epoch    6/20 Batch 1/3 Cost: 1.684383
Epoch    6/20 Batch 2/3 Cost: 3.101316
Epoch    6/20 Batch 3/3 Cost: 1.414109
Epoch    7/20 Batch 1/3 Cost: 0.328983
Epoch    7/20 Batch 2/3 Cost: 5.211092
Epoch    7/20 Batch 3/3 Cost: 1.118716
Epoch    8/20 Batch 1/3 Cost: 0.403220
Epoch    8/2

In [49]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 


훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[154.3330]], grad_fn=<AddmmBackward0>)


# Custom Dataset 적용

In [54]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [55]:
# Dataset 상속
class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
    def __len__(self): 
        return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__(self, idx): 
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y


In [56]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
            ))


Epoch    0/20 Batch 1/3 Cost: 36619.468750
Epoch    0/20 Batch 2/3 Cost: 26480.734375
Epoch    0/20 Batch 3/3 Cost: 7586.458984
Epoch    1/20 Batch 1/3 Cost: 1090.621338
Epoch    1/20 Batch 2/3 Cost: 359.783020
Epoch    1/20 Batch 3/3 Cost: 139.550659
Epoch    2/20 Batch 1/3 Cost: 48.982479
Epoch    2/20 Batch 2/3 Cost: 1.199898
Epoch    2/20 Batch 3/3 Cost: 37.996418
Epoch    3/20 Batch 1/3 Cost: 3.248415
Epoch    3/20 Batch 2/3 Cost: 15.308191
Epoch    3/20 Batch 3/3 Cost: 13.908771
Epoch    4/20 Batch 1/3 Cost: 15.284612
Epoch    4/20 Batch 2/3 Cost: 15.877931
Epoch    4/20 Batch 3/3 Cost: 10.694125
Epoch    5/20 Batch 1/3 Cost: 15.074713
Epoch    5/20 Batch 2/3 Cost: 9.557363
Epoch    5/20 Batch 3/3 Cost: 12.363804
Epoch    6/20 Batch 1/3 Cost: 25.678646
Epoch    6/20 Batch 2/3 Cost: 11.756993
Epoch    6/20 Batch 3/3 Cost: 0.118510
Epoch    7/20 Batch 1/3 Cost: 15.583706
Epoch    7/20 Batch 2/3 Cost: 8.489288
Epoch    7/20 Batch 3/3 Cost: 1.581824
Epoch    8/20 Batch 1/3 Cost: 11.2

In [57]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[156.0870]], grad_fn=<AddmmBackward0>)
